select EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID from Employees;

--Who is the Neena manager?
       --manager id implements employee id, so Neena' manager id=100 ,
       --100 is Steven king's employee id

--for getting manager first name last name , WORKERS.managers_id = MANAGERS.employee_id

SELECT WORKERS.EMPLOYEE_ID, WORKERS.FIRST_NAME, WORKERS.LAST_NAME,WORKERS.MANAGER_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS JOIN EMPLOYEES MANAGERS
ON WORKERS.MANAGER_ID= MANAGERS.EMPLOYEE_ID;


--how can I see all employees even if they do not have any manager?
SELECT WORKERS.EMPLOYEE_ID, WORKERS.FIRST_NAME, WORKERS.LAST_NAME,WORKERS.MANAGER_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS left JOIN EMPLOYEES MANAGERS
ON WORKERS.MANAGER_ID = MANAGERS.EMPLOYEE_ID
ORDER BY WORKERS.EMPLOYEE_ID ASC;
